In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

from utils.data_utils import get_file_lists
from config import  INTERNAL_DIR,  DATA_DIR

file_lists = get_file_lists(os.path.join(DATA_DIR, INTERNAL_DIR))
print("Danh sách file CSV đã tạo:", file_lists)

# Combine all features into a single DataFrame
all_features = []
for file in file_lists:
    df = pd.read_csv(os.path.join(DATA_DIR, INTERNAL_DIR, file))
    all_features.append(df)

df = pd.concat(all_features, ignore_index=True)
print(df.shape)
print(df.head())

Danh sách file CSV đã tạo: ['features_sleep-cassette_SC4001.csv', 'features_sleep-cassette_SC4002.csv', 'features_sleep-cassette_SC4011.csv', 'features_sleep-cassette_SC4012.csv', 'features_sleep-cassette_SC4021.csv', 'features_sleep-cassette_SC4022.csv', 'features_sleep-cassette_SC4031.csv', 'features_sleep-cassette_SC4032.csv', 'features_sleep-cassette_SC4041.csv', 'features_sleep-cassette_SC4042.csv', 'features_sleep-cassette_SC4051.csv', 'features_sleep-cassette_SC4052.csv', 'features_sleep-cassette_SC4061.csv', 'features_sleep-cassette_SC4062.csv', 'features_sleep-cassette_SC4071.csv', 'features_sleep-cassette_SC4072.csv', 'features_sleep-cassette_SC4081.csv', 'features_sleep-cassette_SC4082.csv', 'features_sleep-cassette_SC4091.csv', 'features_sleep-cassette_SC4092.csv', 'features_sleep-cassette_SC4101.csv', 'features_sleep-cassette_SC4102.csv', 'features_sleep-cassette_SC4111.csv', 'features_sleep-cassette_SC4112.csv', 'features_sleep-cassette_SC4121.csv', 'features_sleep-casset

In [3]:
# Preprocessing
X = df.drop(columns=['start_time', 'index', 'label'])
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Cross-validation
rf = RandomForestClassifier(n_estimators=100, random_state=42)
cv_scores = cross_val_score(rf, X_train_scaled, y_train, cv=5)
print("Cross-validation scores:", cv_scores)
print("Average CV score:", np.mean(cv_scores))

rf.fit(X_train_scaled, y_train)
y_pred = rf.predict(X_test_scaled)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Cross-validation scores: [0.76922815 0.77205532 0.7747045  0.77099159 0.77085533]
Average CV score: 0.7715669769835735
Confusion Matrix:
 [[ 9707   410   347    43   212]
 [ 1185  1117  1558    13   490]
 [  454   355 11992   362   580]
 [   76     1   617  1926     2]
 [  396   329   905    14  3606]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.91      0.86     10719
           1       0.50      0.26      0.34      4363
           2       0.78      0.87      0.82     13743
           3       0.82      0.73      0.77      2622
           4       0.74      0.69      0.71      5250

    accuracy                           0.77     36697
   macro avg       0.73      0.69      0.70     36697
weighted avg       0.76      0.77      0.76     36697



In [5]:
import joblib
joblib.dump(model, 'models/random_forest_model.joblib')

['models/random_forest_model.joblib']