In [3]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

from utils.data_utils import get_file_lists

CSV_DIR = 'processed_data'

file_lists = get_file_lists()
print("Danh sách file CSV đã tạo:", file_lists)

# Combine all features into a single DataFrame
all_features = []
for file in file_lists:
    df = pd.read_csv(os.path.join(CSV_DIR, file))
    all_features.append(df)

df = pd.concat(all_features, ignore_index=True)
print(df.shape)
print(df.head())

Danh sách file CSV đã tạo: ['features_sleep-cassette_SC4001.csv', 'features_sleep-cassette_SC4002.csv', 'features_sleep-cassette_SC4011.csv', 'features_sleep-cassette_SC4012.csv', 'features_sleep-cassette_SC4021.csv', 'features_sleep-cassette_SC4022.csv', 'features_sleep-cassette_SC4031.csv', 'features_sleep-cassette_SC4032.csv', 'features_sleep-cassette_SC4041.csv', 'features_sleep-cassette_SC4042.csv', 'features_sleep-cassette_SC4051.csv', 'features_sleep-cassette_SC4052.csv', 'features_sleep-cassette_SC4061.csv', 'features_sleep-cassette_SC4062.csv', 'features_sleep-cassette_SC4071.csv', 'features_sleep-cassette_SC4072.csv', 'features_sleep-cassette_SC4081.csv', 'features_sleep-cassette_SC4082.csv', 'features_sleep-cassette_SC4091.csv', 'features_sleep-cassette_SC4092.csv', 'features_sleep-cassette_SC4101.csv', 'features_sleep-cassette_SC4102.csv', 'features_sleep-cassette_SC4111.csv', 'features_sleep-cassette_SC4112.csv', 'features_sleep-cassette_SC4121.csv', 'features_sleep-casset

In [4]:
# Preprocessing
X = df.drop(columns=['start_time', 'index', 'label'])
y = df['label']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train a simple model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.91      0.87     14014
           1       0.47      0.22      0.30      5078
           2       0.78      0.88      0.83     17763
           3       0.82      0.75      0.78      3857
           5       0.73      0.67      0.70      6878

    accuracy                           0.78     47590
   macro avg       0.73      0.69      0.70     47590
weighted avg       0.76      0.78      0.76     47590

[[12774   480   431    42   287]
 [ 1408  1139  1730    25   776]
 [  629   383 15554   545   652]
 [   86     2   882  2883     4]
 [  591   413  1238    22  4614]]


In [ ]:
import joblib
joblib.dump(model, 'models/random_forest_model.joblib')

NameError: name 'model' is not defined